
package dst3.ejb.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "JobSearch", targetNamespace = "http://wsDef.ejb.dst3/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobSearch {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<dst3.ejb.ws.SearchResultDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://wsDef.ejb.dst3/", className = "dst3.ejb.ws.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://wsDef.ejb.dst3/", className = "dst3.ejb.ws.SearchResponse")
    public List<SearchResultDto> search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
